### ISSUE TITLE
Cannot use phpbrew on ubuntu20 (php7.4)

### ISSUE THREAD

**Issue by juzi5201314** [phpbrew/phpbrew#1189]
### Output

```
Downloading https://secure.php.net/releases/index.php?json&version=7&max=100 via curl extension
[==================================================================] 178.00/178.00B 100%
CurlKit\CurlException:  at [The Location header can not be found: HTTP/1.1 200 Connection established]
Trace:

PHP Notice:  Undefined index: args in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 86
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter::dumpArgs() must be of the type array, null given, called in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 86 and defined in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php:68
Stack trace:
#0 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php(86): CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dumpArgs()
#1 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/ProductionExceptionPrinter.php(14): CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dumpTraceInPhar()
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php(149): CLIFramework\ExceptionPrinter\ProductionExceptionPrinter->dump()
#3 phar:///usr/local/bin/phpbrew/bin/phpbrew(26): PhpBrew\Console->runWithTry()
 in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 68
```

### Command

`phpbrew known`

### Platform

OS:

`Ubuntu 20.04 (windows subsystem for linux)`

Running PHP: 

`PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )`

**Comment by juzi5201314** [comment]
It seems to be because the `$entry['args']` of https://github.com/c9s/CLIFramework/blob/master/src/ExceptionPrinter/DevelopmentExceptionPrinter.php#L84 is null.

**Comment by juzi5201314** [comment]
It still seems to be the #1011 issue. I can't use the master branch and there will be problems. But I checkout to https://github.com/phpbrew/phpbrew/pull/1038/commits/53123eca0e8a7f97b4908711209bc8fa25288e94, now it can be used normally.
