### ISSUE TITLE
Cannot switch to PHP v8.2.8

### ISSUE THREAD

**Issue by tarach** [phpbrew/phpbrew#1350]
```
seb@DESKTOP-IBKGLIL:~$ phpbrew list
* (system)
  php-8.2.8
seb@DESKTOP-IBKGLIL:~$ phpbrew known
Read local release list (last update: 2023-08-15 11:49:07 UTC).
You can run `phpbrew update` or `phpbrew known --update` to get a newer release list.
8.2: 8.2.8, 8.2.7, 8.2.6, 8.2.5, 8.2.4, 8.2.3, 8.2.2, 8.2.1 ...
8.1: 8.1.22, 8.1.21, 8.1.20, 8.1.19, 8.1.18, 8.1.17, 8.1.16, 8.1.15 ...
8.0: 8.0.30, 8.0.29, 8.0.28, 8.0.27, 8.0.26, 8.0.25, 8.0.24, 8.0.23 ...
7.4: 7.4.33, 7.4.32, 7.4.30, 7.4.29, 7.4.28, 7.4.27, 7.4.26, 7.4.25 ...
7.3: 7.3.33, 7.3.32, 7.3.31, 7.3.30, 7.3.29, 7.3.28, 7.3.27, 7.3.26 ...
7.2: 7.2.34, 7.2.33, 7.2.32, 7.2.31, 7.2.30, 7.2.29, 7.2.28, 7.2.27 ...
7.1: 7.1.33, 7.1.32, 7.1.31, 7.1.30, 7.1.29, 7.1.28, 7.1.27, 7.1.26 ...
7.0: 7.0.33, 7.0.32 ...
seb@DESKTOP-IBKGLIL:~$ phpbrew use 8.2.8
Exception: You should not see this. If you see this, it means you didn't load the ~/.phpbrew/bashrc script. Please check if bashrc is sourced in your shell.
Trace:

PHP Warning:  Undefined array key "args" in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 86
PHP Fatal error:  Uncaught TypeError: CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter::dumpArgs(): Argument #1 ($args) must be of type array, null given, called in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 86 and defined in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php:68
Stack trace:
#0 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php(86): CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dumpArgs()
#1 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/ProductionExceptionPrinter.php(14): CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dumpTraceInPhar()
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php(149): CLIFramework\ExceptionPrinter\ProductionExceptionPrinter->dump()
#3 phar:///usr/local/bin/phpbrew/bin/phpbrew(26): PhpBrew\Console->runWithTry()
#4 /usr/local/bin/phpbrew(14): require('...')
#5 {main}
  thrown in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 68
```
**edit>
Ok so I'm guessing PHP above 8.2 is not supported yet ?**
```
seb@DESKTOP-IBKGLIL:~$ source ~/.phpbrew/bashrc
seb@DESKTOP-IBKGLIL:~$ phpbrew list

Box Requirements Checker
========================

> Using PHP 8.2.8
> PHP is using the following php.ini file:
  /home/seb/.phpbrew/php/php-8.2.8/etc/cli/php.ini

> Checking Box requirements:
  E.


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.2.5 || <8.2.0" or greater.
```

**Comment by tarach** [comment]
I've switched manually and for now at least it saved the problem. Good thing phpbrew at least helps you install the latest version. 🙂👍

```
export PATH=/home/seb/.phpbrew/php/php-8.2.8/bin:$PATH
```

**Comment by dinoqqq** [comment]
As you can see in the message above:
```
Exception: You should not see this. If you see this, it means you didn't load the ~/.phpbrew/bashrc script. Please check if bashrc is sourced in your shell.
```
Make sure this file always gets sourced.
