### ISSUE TITLE
phpbrew ext install zookeeper

### ISSUE THREAD

**Issue by kaiyulee** [phpbrew/phpbrew#737]
### Failed to install zookeeper with git repo address

```bash
➜  ~ phpbrew ext install https://github.com/andreiz/php-zookeeper.git
===> Downloading from https://github.com/andreiz/php-zookeeper/archive/master.tar.gz
Redirecting to https://codeload.github.com/andreiz/php-zookeeper/tar.gz/master
===> /Users/Kron/.phpbrew/distfiles/php-zookeeper-master.tar.gz downloaded.
===> Extracting to /Users/Kron/.phpbrew/build/php-7.0.6/ext...
===> Rename source directory to /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper...
===> Installing zookeeper extension...
Log stored at: /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper/build.log
Changing directory to /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: make -C /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper  all  >> /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper/build.log 2>&1
Exception: Command failed: make -C /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper  all  >> /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper/build.log 2>&1 returns
Trace:

    0) PhpBrew\Utils::system('make -C /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper  all  >> /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper/build.log 2>&1', CLIFramework\Logger)
    1) PhpBrew\Tasks\MakeTask->make('/Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper', 'all')
    2) PhpBrew\Tasks\MakeTask->run(PhpBrew\Extension\PeclExtension)
    3) PhpBrew\Extension\ExtensionInstaller->install(PhpBrew\Extension\PeclExtension, [])
    4) PhpBrew\Extension\ExtensionManager->installExtension(PhpBrew\Extension\PeclExtension, [])
    5) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('https://github.com/andreiz/php-zookeeper.git')
    6) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['https://github.com/andreiz/php-zookeeper.git'])
    7) CLIFramework\CommandBase->executeWrapper(['https://github.com/andreiz/php-zookeeper.git'])
    8) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'ext', 'install', 'https://github.com/andreiz/php-zookeeper.git'])
    9) CLIFramework\Application->runWithTry(['/usr/local/bin/phpbrew', 'ext', 'install', 'https://github.com/andreiz/php-zookeeper.git'])
    10) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')

➜  ~
```

### Command
```bash
phpbrew ext install https://github.com/andreiz/php-zookeeper.git
```
### Platform

OS:

   OS X EI Captitan

Running PHP: 
phpbrew use php-7.0.6

Installing PHP:
php 5.5.32

**Comment by kaiyulee** [comment]
After `phpbrew self-update`, the error output is:
```bash
➜  ~ phpbrew ext install github:andreiz/php-zookeeper master
Warning: Some extension won't be able to be built with php7. If the extension
supports php7 in another branch or new major version, you will need to specify
the branch name or version name explicitly.

For example, to install memcached extension for php7, use:

    phpbrew ext install github:php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl

Downloading https://github.com/andreiz/php-zookeeper/archive/master.tar.gz via curl extension
Redirecting to https://codeload.github.com/andreiz/php-zookeeper/tar.gz/master
===> Extracting to /Users/Kron/.phpbrew/build/php-7.0.6/ext...
===> Rename source directory to /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper...
===> Installing zookeeper extension...
Log stored at: /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper/build.log
Changing directory to /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper' 'all'  >> '/Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper/build.log' 2>&1
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PhpBrew\Exception\SystemCommandException::__construct() must be an instance of PhpBrew\Build, instance of PhpBrew\Extension\PeclExtension given, called in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 241 and defined in phar:///usr/local/bin/phpbrew/src/PhpBrew/Exception/SystemCommandException.php:13
Stack trace:
#0 phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php(241): PhpBrew\Exception\SystemCommandException->__construct('Command failed:...', Object(PhpBrew\Extension\PeclExtension))
#1 phar:///usr/local/bin/phpbrew/src/PhpBrew/Tasks/MakeTask.php(92): PhpBrew\Utils::system('/usr/bin/make -...', Object(CLIFramework\Logger), Object(PhpBrew\Extension\PeclExtension))
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Tasks/MakeTask.php(17): PhpBrew\Tasks\MakeTask->make('/Users/Kron/.ph...', 'all', Object(PhpBrew\Extension\PeclExtension))
#3 phar:///usr/local/bin/phpbrew/src/PhpBrew/Extension/ExtensionInstaller.php(76): PhpBrew\Tasks\MakeTask->run(Object(PhpBrew in phar:///usr/local/bin/phpbrew/src/PhpBrew/Exception/SystemCommandException.php on line 13

Fatal error: Uncaught TypeError: Argument 2 passed to PhpBrew\Exception\SystemCommandException::__construct() must be an instance of PhpBrew\Build, instance of PhpBrew\Extension\PeclExtension given, called in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 241 and defined in phar:///usr/local/bin/phpbrew/src/PhpBrew/Exception/SystemCommandException.php:13
Stack trace:
#0 phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php(241): PhpBrew\Exception\SystemCommandException->__construct('Command failed:...', Object(PhpBrew\Extension\PeclExtension))
#1 phar:///usr/local/bin/phpbrew/src/PhpBrew/Tasks/MakeTask.php(92): PhpBrew\Utils::system('/usr/bin/make -...', Object(CLIFramework\Logger), Object(PhpBrew\Extension\PeclExtension))
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Tasks/MakeTask.php(17): PhpBrew\Tasks\MakeTask->make('/Users/Kron/.ph...', 'all', Object(PhpBrew\Extension\PeclExtension))
#3 phar:///usr/local/bin/phpbrew/src/PhpBrew/Extension/ExtensionInstaller.php(76): PhpBrew\Tasks\MakeTask->run(Object(PhpBrew in phar:///usr/local/bin/phpbrew/src/PhpBrew/Exception/SystemCommandException.php on line 13
➜  ~
```

**Comment by jhdxr** [comment]
There is somewrong when you build the extension, check /Users/Kron/.phpbrew/build/php-7.0.6/ext/zookeeper/build.log for more detail.

**Comment by kaiyulee** [comment]
@jhdxr maybe cause the zookeeper ext not support php7.

**Comment by jhdxr** [comment]
@kaiyulee according to andreiz/php-zookeeper#69 , php7 is not supported yet.

**Comment by Timandes** [comment]
@kaiyulee can you try https://github.com/Timandes/libzookeeper ?
```
phpbrew ext install https://github.com/Timandes/libzookeeper.git
```

**Comment by kaiyulee** [comment]
@Timandes I'll try it later. Thanks~
