### ISSUE TITLE
Installing redis with php 7.0.7 fails with fatal error

### ISSUE THREAD

**Issue by mirfilip** [phpbrew/phpbrew#748]
### Output
```
$ phpbrew self-update
(success ...)
phpbrew - 1.21.6
cliframework core: 2.5.4

$ php -v | head -1
PHP 7.0.7 (cli) (built: May 26 2016 13:37:39) ( NTS )

$ phpbrew ext install redis
(...)
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/Users/me/.phpbrew/build/php-7.0.7/ext/redis' 'all'  >> '/Users/me/.phpbrew/build/php-7.0.7/ext/redis/build.log' 2>&1
```
```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PhpBrew\Exception\SystemCommandException::__construct() must be an instance of PhpBrew\Build, instance of PhpBrew\Extension\PeclExtension given, called in phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Utils.php on line 255 and defined in phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Exception/SystemCommandException.php:14
Stack trace:
#0 phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Utils.php(255): PhpBrew\Exception\SystemCommandException->__construct('Command failed:...', Object(PhpBrew\Extension\PeclExtension))
#1 phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Tasks/MakeTask.php(93): PhpBrew\Utils::system('/usr/bin/make -...', Object(CLIFramework\Logger), Object(PhpBrew\Extension\PeclExtension))
#2 phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Tasks/MakeTask.php(18): PhpBrew\Tasks\MakeTask->make('/Users/me...', 'all', Object(PhpB in phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Exception/SystemCommandException.php on line 14

Fatal error: Uncaught TypeError: Argument 2 passed to PhpBrew\Exception\SystemCommandException::__construct() must be an instance of PhpBrew\Build, instance of PhpBrew\Extension\PeclExtension given, called in phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Utils.php on line 255 and defined in phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Exception/SystemCommandException.php on line 14

TypeError: Argument 2 passed to PhpBrew\Exception\SystemCommandException::__construct() must be an instance of PhpBrew\Build, instance of PhpBrew\Extension\PeclExtension given, called in phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Utils.php on line 255 in phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Exception/SystemCommandException.php on line 14
```
```
Call Stack:
    0.0148     760720   1. {main}() /usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar:0
    0.0185     795528   2. require('phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/scripts/phpbrew-emb.php') /usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar:99
    0.0233    1161928   3. PhpBrew\Console->runWithTry() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/scripts/phpbrew-emb.php:2
    0.0233    1161928   4. CLIFramework\Application->run() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Console.php:109
    0.0448    3001736   5. CLIFramework\CommandBase->executeWrapper() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/vendor/corneltek/cliframework/src/Application.php:398
    0.0449    3002352   6. call_user_func_array:{phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/vendor/corneltek/cliframework/src/CommandBase.php:845}() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/vendor/corneltek/cliframework/src/CommandBase.php:845
    0.0450    3002744   7. PhpBrew\Command\ExtensionCommand\InstallCommand->execute() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/vendor/corneltek/cliframework/src/CommandBase.php:845
    4.8355    3490800   8. PhpBrew\Extension\ExtensionManager->installExtension() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Command/ExtensionCommand/InstallCommand.php:185
    4.8360    3509936   9. PhpBrew\Extension\ExtensionInstaller->install() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Extension/ExtensionManager.php:79
    9.1946    3533720  10. PhpBrew\Tasks\MakeTask->run() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Extension/ExtensionInstaller.php:76
    9.1946    3533720  11. PhpBrew\Tasks\MakeTask->make() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Tasks/MakeTask.php:18
    9.2056    3534552  12. PhpBrew\Utils::system() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Tasks/MakeTask.php:93
    9.6563    3550800  13. PhpBrew\Exception\SystemCommandException->__construct() phar:///usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar/src/PhpBrew/Utils.php:255
```

**EDIT**: 
Upon inspecting the build log, I noticed I used a wrong branch for php7. Anyway, IIRC fatal error was not an expected behaviour when extension fails to compile so it can point to other bug.

**Comment by c9s** [comment]
You should run:

    phpbrew ext install github:phpredis/phpredis php7

**Comment by c9s** [comment]
Please see https://github.com/corneltek/UniversalCache#hacking for more details

**Comment by c9s** [comment]
Cookbook updated https://github.com/phpbrew/phpbrew/wiki/PHP7

**Comment by mirfilip** [comment]
I know I should have. See my edit. I just noted that PHP Fatal Error which you can see in the logs didn't use to be the result of doing the same thing in previous versions. Maybe it's a regression bug. Didn't it use to return a clean error message that the extension couldn't have been built?

**Comment by c9s** [comment]
Yes, this was fixed a hour ago
